[workspace]
authors = ["kerchner@gwu.edu <kerchner@gwu.edu>"]
channels = ["conda-forge", "bioconda"]
name = "manuscript_parathaa"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
r-docopt = ">=0.7.2,<0.8"
anadama2 = ">=0.10.0,<0.11"
mothur = ">=1.48.3,<2"
r-dplyr = ">=1.1.4,<2"
r-stringr = ">=1.6.0,<2"
r-tidyr = ">=1.3.2,<2"
r-seqinr = ">=4.2_36,<5"
